# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fhi-web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://skaleregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3438b914b9b14fb592468d5fd23c3b62 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0b93f5a6d8a645bab33d2dc2bc31ead2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: skaleregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3438b914b9b14fb592468d5fd23c3b62 }}/skaleregistry/fhi-container-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fhi-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a65561048848468484c8914b87430a95 }}
        images: 'skaleregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3438b914b9b14fb592468d5fd23c3b62 }}/skaleregistry/fhi-container-app:${{ github.sha }}'